---
title: "EM Algorithm on R1 = 3 and R2 = 2 Regimes"
output: html_document
date: "2024-06-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
seed.list <- c(43,597,731,1066,1170,1215,1348,1415,1534,1556,1588,1605,1611,
               1660,1662,1688,1697,1704,1707,1741,1801,1805,1815,1945,2022)

file.names <- numeric(0) 
for (i in 1:length(seed.list)) {
  file.names[i] <- paste0("EMR-R1.3-R2.2_", seed.list[i], ".rds")
}

BIC.6pos_r1.3_r2.2 <- numeric(length(seed.list))
```

# R1 = 3, R2 = 2, POS = 9, 7 Undisputed
```{r}
for (w in 1:25) {

print(seed.list[w])
paul_pos.list <- readRDS("paul_6pos.rds")

R = 5
R1 = 3
R2 = R - R1
stateList <- factor(c("AD", "I", "N", "P", "RA", "V"))
stateList <- sort(stateList)
K <- length(stateList)
A <- diag(R)

sent_leng <- numeric(13)
for (i in 1:13) {
  sent_leng[i] <- length(paul_pos.list[[i]])
}

N <- sent_leng
L <- 13
d1 <- 7
r.mn_id <- matrix(NA, nrow = L, ncol = max(N))
B <- matrix(0, nrow = R1, ncol = R)

pi_reg <- c(0.45, 0.25, 0.1, 0.1, 0.1)
for (i in 1:R1){
  B[i,i] <- 1
}

set.seed(seed.list[w])
for (i in 1:L){
  if (i <= d1){
    aa <- B%*%pi_reg # select R_1 regimes from pi_reg
    pit <- aa/norm(aa) # normalized aa
    Rcurrent <- R1
  }else {
    pit <- pi_reg
    Rcurrent <- R
  }
  r.mn_id[i,1:N[i]] <- apply(rmultinom(N[i], 1, pit), 2,which.max) ## generate regime id
}


## Estimate initial A, Alpha, and Gamma matrices
### A matrix

A <- matrix(0, nrow = R, ncol = R)

##### D_1 books #####
# Romans
for (i in 1:R) {
  for (j in 1:R) {
    counter <- numeric(0)
    for (k in 1:(N[1]-1)) {
      if (r.mn_id[1,k] == i && r.mn_id[1,k+1] == j) {
        counter <- append(counter, 1)
      }
    }
    A[i,j] <- A[i,j] + sum(counter)
  }
}

# 1 Corinthians
for (i in 1:R) {
  for (j in 1:R) {
    counter <- numeric(0)
    for (k in 1:(N[2]-1)) {
      if (r.mn_id[2,k] == i && r.mn_id[2,k+1] == j) {
        counter <- append(counter, 1)
      }
    }
    A[i,j] <- A[i,j] + sum(counter)
  }
}

# 2 Corinthians
for (i in 1:R) {
  for (j in 1:R) {
    counter <- numeric(0)
    for (k in 1:(N[3]-1)) {
      if (r.mn_id[3,k] == i && r.mn_id[3,k+1] == j) {
        counter <- append(counter, 1)
      }
    }
    A[i,j] <- A[i,j] + sum(counter)
  }
}

# Galatians
for (i in 1:R) {
  for (j in 1:R) {
    counter <- numeric(0)
    for (k in 1:(N[4]-1)) {
      if (r.mn_id[4,k] == i && r.mn_id[4,k+1] == j) {
        counter <- append(counter, 1)
      }
    }
    A[i,j] <- A[i,j] + sum(counter)
  }
}

# Philippians
for (i in 1:R) {
  for (j in 1:R) {
    counter <- numeric(0)
    for (k in 1:(N[5]-1)) {
      if (r.mn_id[5,k] == i && r.mn_id[5,k+1] == j) {
        counter <- append(counter, 1)
      }
    }
    A[i,j] <- A[i,j] + sum(counter)
  }
}

# 1 Thessalonians
for (i in 1:R) {
  for (j in 1:R) {
    counter <- numeric(0)
    for (k in 1:(N[6]-1)) {
      if (r.mn_id[6,k] == i && r.mn_id[6,k+1] == j) {
        counter <- append(counter, 1)
      }
    }
    A[i,j] <- A[i,j] + sum(counter)
  }
}

# Philemon
for (i in 1:R) {
  for (j in 1:R) {
    counter <- numeric(0)
    for (k in 1:(N[7]-1)) {
      if (r.mn_id[7,k] == i && r.mn_id[7,k+1] == j) {
        counter <- append(counter, 1)
      }
    }
    A[i,j] <- A[i,j] + sum(counter)
  }
}

##### D_2 books: not PE #####
# Ephesians
for (i in 1:R) {
  for (j in 1:R) {
    counter <- numeric(0)
    for (k in 1:(N[8]-1)) {
      if (r.mn_id[8,k] == i && r.mn_id[8,k+1] == j) {
        counter <- append(counter, 1)
      }
    }
    A[i,j] <- A[i,j] + sum(counter)
  }
}

# Colossians
for (i in 1:R) {
  for (j in 1:R) {
    counter <- numeric(0)
    for (k in 1:(N[9]-1)) {
      if (r.mn_id[9,k] == i && r.mn_id[9,k+1] == j) {
        counter <- append(counter, 1)
      }
    }
    A[i,j] <- A[i,j] + sum(counter)
  }
}

# 2 Thessalonians
for (i in 1:R) {
  for (j in 1:R) {
    counter <- numeric(0)
    for (k in 1:(N[10]-1)) {
      if (r.mn_id[10,k] == i && r.mn_id[10,k+1] == j) {
        counter <- append(counter, 1)
      }
    }
    A[i,j] <- A[i,j] + sum(counter)
  }
}

#### D_2 books: PE #####
# 1 Timothy
for (i in 1:R) {
  for (j in 1:R) {
    counter <- numeric(0)
    for (k in 1:(N[11]-1)) {
      if (r.mn_id[11,k] == i && r.mn_id[11,k+1] == j) {
        counter <- append(counter, 1)
      }
    }
    A[i,j] <- A[i,j] + sum(counter)
  }
}

# 2 Timothy
for (i in 1:R) {
  for (j in 1:R) {
    counter <- numeric(0)
    for (k in 1:(N[12]-1)) {
      if (r.mn_id[12,k] == i && r.mn_id[12,k+1] == j) {
        counter <- append(counter, 1)
      }
    }
    A[i,j] <- A[i,j] + sum(counter)
  }
}

# Titus
for (i in 1:R) {
  for (j in 1:R) {
    counter <- numeric(0)
    for (k in 1:(N[13]-1)) {
      if (r.mn_id[13,k] == i && r.mn_id[13,k+1] == j) {
        counter <- append(counter, 1)
      }
    }
    A[i,j] <- A[i,j] + sum(counter)
  }
}

# Normalize rows
A <- round(A/rowSums(A), 4)
colnames(A) <- c("R1","R2","R3","R4","R5")
rownames(A) <- c("R1","R2","R3","R4","R5")


### Alpha Matrix

r1 <- vector(mode = "list", length = 0)
r2 <- vector(mode = "list", length = 0)
r3 <- vector(mode = "list", length = 0)
r4 <- vector(mode = "list", length = 0)
r5 <- vector(mode = "list", length = 0)

Alpha <- matrix(0, nrow = R, ncol = length(stateList))

for (i in 1:L) {
  book <- paul_pos.list[[i]]
  r1 <- append(r1, book[r.mn_id[i,1:length(paul_pos.list[[i]])] == 1])
  r2 <- append(r2, book[r.mn_id[i,1:length(paul_pos.list[[i]])] == 2])
  r3 <- append(r3, book[r.mn_id[i,1:length(paul_pos.list[[i]])] == 3])
  r4 <- append(r4, book[r.mn_id[i,1:length(paul_pos.list[[i]])] == 4])
  r5 <- append(r5, book[r.mn_id[i,1:length(paul_pos.list[[i]])] == 5])
}

r1_vec <- factor(unlist(r1))
r2_vec <- factor(unlist(r2))
r3_vec <- factor(unlist(r3))
r4_vec <- factor(unlist(r4))
r5_vec <- factor(unlist(r5))

for (i in 1:length(stateList)) {
    q <- as.character(stateList[i])
    Alpha[1,i] <- sum(r1_vec == q)/length(r1_vec)
}

for (i in 1:length(stateList)) {
    q <- as.character(stateList[i])
    Alpha[2,i] <- sum(r2_vec == q)/length(r2_vec)
}

for (i in 1:length(stateList)) {
    q <- as.character(stateList[i])
    Alpha[3,i] <- sum(r3_vec == q)/length(r3_vec)
}

for (i in 1:length(stateList)) {
    q <- as.character(stateList[i])
    Alpha[4,i] <- sum(r4_vec == q)/length(r4_vec)
}

for (i in 1:length(stateList)) {
    q <- as.character(stateList[i])
    Alpha[5,i] <- sum(r5_vec == q)/length(r5_vec)
}

colnames(Alpha) <- sort(stateList)
rownames(Alpha) <- c("R1", "R2", "R3", "R4","R5")
rowSums(Alpha)


### Gamma matrix
Gamma_array <- array(0, dim=c(R,K,K))

# Regime 1
regime_1 <- matrix(data = NA, K, K)

for (i in 1:K) {
  for (j in 1:K) {
    counter <- numeric(0)
    for (k in 1:(length(r1_vec)-1)) {
      if (r1_vec[k] == stateList[i] && r1_vec[k+1] == stateList[j]) {
        counter <- append(counter, 1)
      }
      regime_1[i,j] <- sum(counter)
    }
  }
}

# Regime 2
regime_2 <- matrix(data = NA, K, K)

for (i in 1:K) {
  for (j in 1:K) {
    counter <- numeric(0)
    for (k in 1:(length(r2_vec)-1)) {
      if (r2_vec[k] == stateList[i] && r2_vec[k+1] == stateList[j]) {
        counter <- append(counter, 1)
      }
      regime_2[i,j] <- sum(counter)
    }
  }
}

# Regime 3
regime_3 <- matrix(data = NA, K, K)

for (i in 1:K) {
  for (j in 1:K) {
    counter <- numeric(0)
    for (k in 1:(length(r3_vec)-1)) {
      if (r3_vec[k] == stateList[i] && r3_vec[k+1] == stateList[j]) {
        counter <- append(counter, 1)
      }
      regime_3[i,j] <- sum(counter)
    }
  }
}

# Regime 4
regime_4 <- matrix(data = NA, K, K)

for (i in 1:K) {
  for (j in 1:K) {
    counter <- numeric(0)
    for (k in 1:(length(r4_vec)-1)) {
      if (r4_vec[k] == stateList[i] && r4_vec[k+1] == stateList[j]) {
        counter <- append(counter, 1)
      }
      regime_4[i,j] <- sum(counter)
    }
  }
}

# Regime 5
regime_5 <- matrix(data = NA, K, K)

for (i in 1:K) {
  for (j in 1:K) {
    counter <- numeric(0)
    for (k in 1:(length(r5_vec)-1)) {
      if (r5_vec[k] == stateList[i] && r5_vec[k+1] == stateList[j]) {
        counter <- append(counter, 1)
      }
      regime_5[i,j] <- sum(counter)
    }
  }
}

Gamma_array[1,,] <- round(regime_1/sum(regime_1),5)
Gamma_array[2,,] <- round(regime_2/sum(regime_2),5)
Gamma_array[3,,] <- round(regime_3/sum(regime_3),5)
Gamma_array[4,,] <- round(regime_4/sum(regime_4),5)
Gamma_array[5,,] <- round(regime_5/sum(regime_5),5)

### Add small values for 0's
for (i in 1:R) {
  draw <- Gamma_array[i,,]
  draw[draw == 0] <- 1e-6
  Gamma_array[i,,] <- draw
}


## EM Algorithm: (1) R1 = 3, (2) R = 5, (3) POS = 6
print(file.names[w])
EMR <- EM(paul_pos.list, R1, d1, N, pi_reg, A, Alpha, Gamma_array, stateList, 0.001, 50)
saveRDS(EMR,file.names[w])

BIC.6pos_r1.3_r2.2[w] <- EMR$BIC
}
```



