---
title: "Post-Experiment Analysis on R1 = 2, R2 = 1"
author: "Josiah Leinbach"
date: "2024-06-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tseries)
library(dplyr)
library(tidyverse)
```

# R1 = 2, R2 = 1
## Regime Distributions for 1 John
```{r}
rds_2.1_John1 <- readRDS("EMR.John1-R1.2-R2.1-9pos.rds")
styles_mat.John1 <- matrix(data = 0, nrow = 14, ncol = 3)
id <- rds_2.1_John1$id

for (i in 1:14) {
  for (j in 1:3) {
    styles_mat.John1[i,j] <- sum(id[i,] == j, na.rm = T)
  }
}

colnames(styles_mat.John1) <- c("Paul_1", "Paul_2", "Non-Paul_1")

N <- rowSums(styles_mat.John1)
styles_mat.John1 <- as.data.frame(styles_mat.John1)

books_vec <- c("Rom", "Cor.1", "Cor.2", "Gal", "Php", "Thes.1", "Phm", "Eph", "Col", "Thes.2",
               "Tim.1", "Tim.2", "Tit", "John.1")
styles_mat.John1$Book <- books_vec

book.type <- factor(c("Disputed_Non.PE","Undisputed","Undisputed","Disputed_Non.PE","Undisputed", "Johannine",
                      "Undisputed","Undisputed","Undisputed","Undisputed","Disputed_Non.PE",
                      "Disputed_PE","Disputed_PE","Disputed_PE"))

styles_mat.John1 <- styles_mat.John1 %>%
  rowwise() %>%
  mutate(Total_sent = sum(Paul_1, Paul_2, `Non-Paul_1`)) %>%
  mutate(Paul_perc = sum(Paul_1, Paul_2)/sum(Paul_1, Paul_2, `Non-Paul_1`)) %>%
  relocate(Book, .before = Paul_1) %>%
  arrange(Book) %>%
  add_column(Class = book.type) %>%
  relocate(Class, .before = Paul_1)
```

## Regime Distributions for 2 John
```{r}
rds_2.1_John2 <- readRDS("EMR.John2-R1.2-R2.1-9pos.rds")
styles_mat.John2 <- matrix(data = 0, nrow = 14, ncol = 3)
id <- rds_2.1_John2$id

for (i in 1:14) {
  for (j in 1:3) {
    styles_mat.John2[i,j] <- sum(id[i,] == j, na.rm = T)
  }
}

colnames(styles_mat.John2) <- c("Paul_1", "Paul_2", "Non-Paul_1")

N <- rowSums(styles_mat.John2)
styles_mat.John2 <- as.data.frame(styles_mat.John2)

books_vec <- c("Rom", "Cor.1", "Cor.2", "Gal", "Php", "Thes.1", "Phm", "Eph", "Col", "Thes.2",
               "Tim.1", "Tim.2", "Tit", "John.2")
styles_mat.John2$Book <- books_vec

book.type <- factor(c("Disputed_Non.PE","Undisputed","Undisputed","Disputed_Non.PE","Undisputed", "Johannine",
                      "Undisputed","Undisputed","Undisputed","Undisputed","Disputed_Non.PE",
                      "Disputed_PE","Disputed_PE","Disputed_PE"))

styles_mat.John2 <- styles_mat.John2 %>%
  rowwise() %>%
  mutate(Total_sent = sum(Paul_1, Paul_2, `Non-Paul_1`)) %>%
  mutate(Paul_perc = sum(Paul_1, Paul_2)/sum(Paul_1, Paul_2, `Non-Paul_1`)) %>%
  relocate(Book, .before = Paul_1) %>%
  arrange(Book) %>%
  add_column(Class = book.type) %>%
  relocate(Class, .before = Paul_1)
```

## Regime Distributions for 3 John
```{r}
rds_2.1_John3 <- readRDS("EMR.John3-R1.2-R2.1-9pos.rds")
styles_mat.John3 <- matrix(data = 0, nrow = 14, ncol = 3)
id <- rds_2.1_John3$id

for (i in 1:14) {
  for (j in 1:3) {
    styles_mat.John3[i,j] <- sum(id[i,] == j, na.rm = T)
  }
}

colnames(styles_mat.John3) <- c("Paul_1", "Paul_2", "Non-Paul_1")

N <- rowSums(styles_mat.John3)
styles_mat.John3 <- as.data.frame(styles_mat.John3)

books_vec <- c("Rom", "Cor.1", "Cor.2", "Gal", "Php", "Thes.1", "Phm", "Eph", "Col", "Thes.2",
               "Tim.1", "Tim.2", "Tit", "John.3")
styles_mat.John3$Book <- books_vec

book.type <- factor(c("Disputed_Non.PE","Undisputed","Undisputed","Disputed_Non.PE","Undisputed", "Johannine",
                      "Undisputed","Undisputed","Undisputed","Undisputed","Disputed_Non.PE",
                      "Disputed_PE","Disputed_PE","Disputed_PE"))

styles_mat.John3 <- styles_mat.John3 %>%
  rowwise() %>%
  mutate(Total_sent = sum(Paul_1, Paul_2, `Non-Paul_1`)) %>%
  mutate(Paul_perc = sum(Paul_1, Paul_2)/sum(Paul_1, Paul_2, `Non-Paul_1`)) %>%
  relocate(Book, .before = Paul_1) %>%
  arrange(Book) %>%
  add_column(Class = book.type) %>%
  relocate(Class, .before = Paul_1)
```

# R1 = 2, R2 = 2
## Regime Distributions for 1 John
```{r}
rds_2.2_John1 <- readRDS("EMR.John1-R1.2-R2.2-9pos.rds")
styles_mat.John1 <- matrix(data = 0, nrow = 14, ncol = 4)
id <- rds_2.2_John1$id

for (i in 1:14) {
  for (j in 1:4) {
    styles_mat.John1[i,j] <- sum(id[i,] == j, na.rm = T)
  }
}

colnames(styles_mat.John1) <- c("Paul_1", "Paul_2", "Non-Paul_1", "Non-Paul_2")

N <- rowSums(styles_mat.John1)
styles_mat.John1 <- as.data.frame(styles_mat.John1)

books_vec <- c("Rom", "Cor.1", "Cor.2", "Gal", "Php", "Thes.1", "Phm", "Eph", "Col", "Thes.2",
               "Tim.1", "Tim.2", "Tit", "John.1")
styles_mat.John1$Book <- books_vec

book.type <- factor(c("Disputed_Non.PE","Undisputed","Undisputed","Disputed_Non.PE","Undisputed", "Johannine",
                      "Undisputed","Undisputed","Undisputed","Undisputed","Disputed_Non.PE",
                      "Disputed_PE","Disputed_PE","Disputed_PE"))

styles_mat.John1 <- styles_mat.John1 %>%
  rowwise() %>%
  mutate(Total_sent = sum(Paul_1, Paul_2, `Non-Paul_1`)) %>%
  mutate(Paul_perc = sum(Paul_1, Paul_2)/sum(Paul_1, Paul_2, `Non-Paul_1`)) %>%
  relocate(Book, .before = Paul_1) %>%
  arrange(Book) %>%
  add_column(Class = book.type) %>%
  relocate(Class, .before = Paul_1)
```

## Regime Distributions for 2 John
```{r}
rds_2.2_John2 <- readRDS("EMR.John2-R1.2-R2.2-9pos.rds")
styles_mat.John2 <- matrix(data = 0, nrow = 14, ncol = 4)
id <- rds_2.2_John2$id

for (i in 1:14) {
  for (j in 1:4) {
    styles_mat.John2[i,j] <- sum(id[i,] == j, na.rm = T)
  }
}

colnames(styles_mat.John2) <- c("Paul_1", "Paul_2", "Non-Paul_1", "Non-Paul_2")

N <- rowSums(styles_mat.John2)
styles_mat.John2 <- as.data.frame(styles_mat.John2)

books_vec <- c("Rom", "Cor.1", "Cor.2", "Gal", "Php", "Thes.1", "Phm", "Eph", "Col", "Thes.2",
               "Tim.1", "Tim.2", "Tit", "John.2")
styles_mat.John2$Book <- books_vec

book.type <- factor(c("Disputed_Non.PE","Undisputed","Undisputed","Disputed_Non.PE","Undisputed", "Johannine",
                      "Undisputed","Undisputed","Undisputed","Undisputed","Disputed_Non.PE",
                      "Disputed_PE","Disputed_PE","Disputed_PE"))

styles_mat.John2 <- styles_mat.John2 %>%
  rowwise() %>%
  mutate(Total_sent = sum(Paul_1, Paul_2, `Non-Paul_1`)) %>%
  mutate(Paul_perc = sum(Paul_1, Paul_2)/sum(Paul_1, Paul_2, `Non-Paul_1`)) %>%
  relocate(Book, .before = Paul_1) %>%
  arrange(Book) %>%
  add_column(Class = book.type) %>%
  relocate(Class, .before = Paul_1)
```

## Regime Distributions for 3 John
```{r}
rds_2.2_John3 <- readRDS("EMR.John3-R1.2-R2.2-9pos.rds")
styles_mat.John3 <- matrix(data = 0, nrow = 14, ncol = 4)
id <- rds_2.2_John3$id

for (i in 1:14) {
  for (j in 1:4) {
    styles_mat.John3[i,j] <- sum(id[i,] == j, na.rm = T)
  }
}

colnames(styles_mat.John3) <- c("Paul_1", "Paul_2", "Non-Paul_1", "Non-Paul_2")

N <- rowSums(styles_mat.John3)
styles_mat.John3 <- as.data.frame(styles_mat.John3)

books_vec <- c("Rom", "Cor.1", "Cor.2", "Gal", "Php", "Thes.1", "Phm", "Eph", "Col", "Thes.2",
               "Tim.1", "Tim.2", "Tit", "John.3")
styles_mat.John3$Book <- books_vec

book.type <- factor(c("Disputed_Non.PE","Undisputed","Undisputed","Disputed_Non.PE","Undisputed", "Johannine",
                      "Undisputed","Undisputed","Undisputed","Undisputed","Disputed_Non.PE",
                      "Disputed_PE","Disputed_PE","Disputed_PE"))

styles_mat.John3 <- styles_mat.John3 %>%
  rowwise() %>%
  mutate(Total_sent = sum(Paul_1, Paul_2, `Non-Paul_1`)) %>%
  mutate(Paul_perc = sum(Paul_1, Paul_2)/sum(Paul_1, Paul_2, `Non-Paul_1`)) %>%
  relocate(Book, .before = Paul_1) %>%
  arrange(Book) %>%
  add_column(Class = book.type) %>%
  relocate(Class, .before = Paul_1)
```

# Hebrews + Johannine Letters
## Herbrews and 1 John
```{r}
rds_2.2_HJ1 <- readRDS("EMR.HJ-R1.2-R2.2-9pos.rds")
styles_mat.HJ1 <- matrix(data = 0, nrow = 15, ncol = 4)
id <- rds_2.2_HJ1$id

for (i in 1:15) {
  for (j in 1:4) {
    styles_mat.HJ1[i,j] <- sum(id[i,] == j, na.rm = T)
  }
}

colnames(styles_mat.HJ1) <- c("Paul_1", "Paul_2", "Non-Paul_1", "Non-Paul_2")

N <- rowSums(styles_mat.HJ1)
styles_mat.HJ1 <- as.data.frame(styles_mat.HJ1)

books_vec <- c("Rom", "Cor.1", "Cor.2", "Gal", "Php", "Thes.1", "Phm", "Eph", "Col", "Thes.2",
               "Tim.1", "Tim.2", "Tit", "Hebrews", "John.1")
styles_mat.HJ1$Book <- books_vec

book.type <- factor(c("Disputed_Non.PE","Undisputed","Undisputed","Disputed_Non.PE","Undisputed", "Attributed",
                      "Johannine", "Undisputed","Undisputed","Undisputed","Undisputed","Disputed_Non.PE",
                      "Disputed_PE","Disputed_PE","Disputed_PE"))

styles_mat.HJ1 <- styles_mat.HJ1 %>%
  rowwise() %>%
  mutate(Total_sent = sum(Paul_1, Paul_2, `Non-Paul_1`, `Non-Paul_2`)) %>%
  mutate(Paul_perc = sum(Paul_1, Paul_2)/sum(Paul_1, Paul_2, `Non-Paul_1`, `Non-Paul_2`)) %>%
  relocate(Book, .before = Paul_1) %>%
  arrange(Book) %>%
  add_column(Class = book.type) %>%
  relocate(Class, .before = Paul_1)
```

## Hebrews and 2 John
```{r}
rds_2.2_HJ2 <- readRDS("EMR.HJ2-R1.2-R2.2-9pos.rds")
styles_mat.HJ2 <- matrix(data = 0, nrow = 15, ncol = 4)
id <- rds_2.2_HJ2$id

for (i in 1:15) {
  for (j in 1:4) {
    styles_mat.HJ2[i,j] <- sum(id[i,] == j, na.rm = T)
  }
}

colnames(styles_mat.HJ2) <- c("Paul_1", "Paul_2", "Non-Paul_1", "Non-Paul_2")

N <- rowSums(styles_mat.HJ2)
styles_mat.HJ2 <- as.data.frame(styles_mat.HJ2)

books_vec <- c("Rom", "Cor.1", "Cor.2", "Gal", "Php", "Thes.1", "Phm", "Eph", "Col", "Thes.2",
               "Tim.1", "Tim.2", "Tit", "Hebrews", "John.2")
styles_mat.HJ2$Book <- books_vec

book.type <- factor(c("Disputed_Non.PE","Undisputed","Undisputed","Disputed_Non.PE","Undisputed", "Attributed",
                      "Johannine", "Undisputed","Undisputed","Undisputed","Undisputed","Disputed_Non.PE",
                      "Disputed_PE","Disputed_PE","Disputed_PE"))

styles_mat.HJ2 <- styles_mat.HJ2 %>%
  rowwise() %>%
  mutate(Total_sent = sum(Paul_1, Paul_2, `Non-Paul_1`, `Non-Paul_2`)) %>%
  mutate(Paul_perc = sum(Paul_1, Paul_2)/sum(Paul_1, Paul_2, `Non-Paul_1`, `Non-Paul_2`)) %>%
  relocate(Book, .before = Paul_1) %>%
  arrange(Book) %>%
  add_column(Class = book.type) %>%
  relocate(Class, .before = Paul_1)
```

## Hebrews and 3 John
```{r}
rds_2.2_HJ3 <- readRDS("EMR.HJ3-R1.2-R2.2-9pos.rds")
styles_mat.HJ3 <- matrix(data = 0, nrow = 15, ncol = 4)
id <- rds_2.2_HJ3$id

for (i in 1:15) {
  for (j in 1:4) {
    styles_mat.HJ3[i,j] <- sum(id[i,] == j, na.rm = T)
  }
}

colnames(styles_mat.HJ3) <- c("Paul_1", "Paul_2", "Non-Paul_1", "Non-Paul_2")

N <- rowSums(styles_mat.HJ3)
styles_mat.HJ3 <- as.data.frame(styles_mat.HJ3)

books_vec <- c("Rom", "Cor.1", "Cor.2", "Gal", "Php", "Thes.1", "Phm", "Eph", "Col", "Thes.2",
               "Tim.1", "Tim.2", "Tit", "Hebrews", "John.3")
styles_mat.HJ3$Book <- books_vec

book.type <- factor(c("Disputed_Non.PE","Undisputed","Undisputed","Disputed_Non.PE","Undisputed", "Attributed",
                      "Johannine", "Undisputed","Undisputed","Undisputed","Undisputed","Disputed_Non.PE",
                      "Disputed_PE","Disputed_PE","Disputed_PE"))

styles_mat.HJ3 <- styles_mat.HJ3 %>%
  rowwise() %>%
  mutate(Total_sent = sum(Paul_1, Paul_2, `Non-Paul_1`, `Non-Paul_2`)) %>%
  mutate(Paul_perc = sum(Paul_1, Paul_2)/sum(Paul_1, Paul_2, `Non-Paul_1`, `Non-Paul_2`)) %>%
  relocate(Book, .before = Paul_1) %>%
  arrange(Book) %>%
  add_column(Class = book.type) %>%
  relocate(Class, .before = Paul_1)
```


